image: node:8.4
before_script:
  - npm i -g create-react-app
stages:
  - prepare
  - build
  - deploy
cache:
  paths:
    - node_modules/
install_dependencies:
  stage: prepare
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
  only:
    - master
  tags:
    - docker
pages:
  stage: deploy
  dependencies:
    - build
  script:
    - echo "hello world"
  only:
    - master
  tags:
    - docker
