image: node:8.4
before_script:
  - cd react
  - npm install -g create-react-app
stages:
  - prepare
  - build
  - deploy
cache:
  paths:
    - react/node_modules/
install_dependencies:
  stage: prepare
  script:
    - npm install
  artifacts:
    paths:
      - react/node_modules/
build:
  stage: build
  script:
    - unset CI
    - npm run build
  artifacts:
    paths:
      - react/build/
  only:
    - master
  tags:
    - docker
pages:
  stage: deploy
  dependencies:
    - build
  script:
    - mkdir ../public/
    - cp -R build/* ../public/
  artifacts:
    paths:
    - public/
  only:
    - master
  tags:
    - docker
